[package]
name = "lesson-24-x"
version = "0.1.0"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]

[dependencies]
gl = { path = "../lib/gl" }
failure = "0.1"

[features]
gl_debug = ["gl/debug"]
alloc_debug = []