[package]
name = "lesson_10_render_gl_derive"
version = "0.1.0"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]

[dependencies]
quote = "0.3.15"
syn = "0.11.11"
synstructure = "0.6.0"

[lib]
proc-macro = true